-- AlterTable
ALTER TABLE `entry` ADD COLUMN `timeIn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `exit` ADD COLUMN `timeOut` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
